version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - laravel
      # - rails
      # - node
      - java
      # - python

  # laravel:
  #   build: ./laravel-app
  #   volumes:
  #     - ./laravel-app:/var/www/html
  #   expose:
  #     - 80
  #   environment:
  #     DB_HOST: mysql
  #     DB_DATABASE: laravel_db
  #     DB_USERNAME: appuser
  #     DB_PASSWORD: secret

  # rails:
  #   build: ./rails-app
  #   expose:
  #     - 3000
  #   environment:
  #     DATABASE_HOST: mysql
  #     DATABASE_NAME: rails_db
  #     DATABASE_USER: appuser
  #     DATABASE_PASSWORD: secret
  #   depends_on:
  #     - mysql

  # node:
  #   build: ./node-app
  #   expose:
  #     - 3001
  #   environment:
  #     DB_HOST: mysql
  #     DB_NAME: node_db
  #     DB_USER: appuser
  #     DB_PASS: secret

  java:
    build:
      context: ./java-app
      dockerfile: Dockerfile.dev
    # volumes:
    #   - ./java-app:/app
    #   - ~/.m2:/root/.m2
    volumes:
      - ./java-app/src:/app/src
      - ./java-app/pom.xml:/app/pom.xml
      - ./java-app/.mvn:/app/.mvn
      - ./java-app/mvnw:/app/mvnw
      - ~/.m2:/root/.m2
      - ./java-app/src/main/resources/templates:/app/src/main/resources/templates
    expose:
      - 8080
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      DB_HOST: mysql
      DB_NAME: java_db
      DB_USER: appuser
      DB_PASS: secret


  # python:
  #   build: ./python-app
  #   expose:
  #     - 5000
  #   environment:
  #     DB_HOST: mysql
  #     DB_NAME: python_db
  #     DB_USER: appuser
  #     DB_PASS: secret

  mysql:
    image: mysql:8.0
    container_name: shared-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
