server {
    listen 80;

    location /laravel/ {
        proxy_pass http://laravel:80/;
        rewrite ^/laravel(/.*)$ $1 break;
        proxy_set_header Host $host;
    }

    location /rails/ {
        proxy_pass http://rails:3000/;
        rewrite ^/rails(/.*)$ $1 break;
        proxy_set_header Host $host;
    }

    location /node/ {
        proxy_pass http://node:3001/;
        rewrite ^/node(/.*)$ $1 break;
        proxy_set_header Host $host;
    }

    location /java/ {
        proxy_pass http://java:8080/;
        rewrite ^/java(/.*)$ $1 break;
        proxy_set_header Host $host;
    }

    location /python/ {
        proxy_pass http://python:5000/;
        rewrite ^/python(/.*)$ $1 break;
        proxy_set_header Host $host;
    }
}
