server {
    listen 80;
    server_name localhost;

    # location /laravel/ {
    #     alias /var/www/html/public/;
    #     index index.php index.html;
    #     try_files $uri $uri/ /index.php?$query_string;

    #     location ~ \.php$ {
    #         include fastcgi_params;
    #         fastcgi_pass laravel:9000;  # ここ要注意（ApacheではなくPHP-FPM向け設定）
    #         fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
    #     }
    # }

    location /laravel/ {
        proxy_pass http://laravel:80/;
    }

    location /rails/ {
        proxy_pass http://rails:3000/;
    }

    location /node/ {
        proxy_pass http://node:3001/;
    }

    location /java/ {
        proxy_pass http://java:8080/;
    }

    location /python/ {
        proxy_pass http://python:5000/;
    }
}
